### ISSUE TITLE
1.16.5 Messages_en.yml Formatting Error

### ISSUE THREAD

**Issue by rktfier** [kangarko/Confiscate#118] opened 2021-04-23 10:28 UTC
I have a rather interesting find in this plugin. 3 days ago i started using Confiscate but it kept giving me errors about default 'messages_en.yml' lacking an Object. But i never changed anything in that file so i went and checked it but it seemed fine, no problems at the file. I got this error multiple times. Now this is one of the error messages i got : 

`Default 'messages_en.yml' lacks an Object at 'Log.Hacked_Potıon.Type'`

As you can see instead of "Potion" type it says "Potıon" so i went to messages file and replaced `Hacked_Potion:` with `Hacked_Potıon:` and my error changed to : 

`Default 'messages_en.yml' lacks an Object at 'Log.Infınıte_Potıon.Type'`

so i went and replaced `Infınıte_Potion:` with `Infınıte_Potıon:` in the messages_en.yml file and it gave me another error : 

`Default 'messages_en.yml' lacks an Object at 'Log.Enchant_Too_Hıgh.Type'`

I did the same, replacing "i" with "ı" and it worked but it gave me another error. So instead of replacing them i decided to create a new issue here.

I am using Paper 1.16.5 613 with Java 11 ( Eclipse OpenJ9 ) in Windows Server 2012, please inform if more information is required.

**Comment by kangarko** [comment] 2021-04-29 17:28
That is a system encoding issue, looks like you're not on an English version of your operating system. We had a customer from ChatControl had this issue a year ago, unfortunately I could never reproduce this (he was running Turkish OS I think), and it got fixed by him toggling UTF support in his Windows and using Notepad++ to open any files.

**Closed by kangarko** 2021-04-29 17:28 UTC
Labels: issue
