### ISSUE TITLE
Elytra's not being taken from players

### ISSUE THREAD

**Issue by dwaynehulsman** [kangarko/Confiscate#8] opened 2017-06-26 17:14 UTC
Hello,

We run Confiscate 1.3.5 and here is my Item section in the config:
`Items:
  Confiscate:
  - SOIL
  - ELYTRA
  Confiscate_Survival:
  - COMMAND
  - BARRIER
  - STRUCTURE_BLOCK
  - COMMAND_MINECART
  - white_shulker_box
  - orange_shulker_box
  - magenta_shulker_box
  - light_blue_shulker_box
  - yellow_shulker_box
  - lime_shulker_box
  - pink_shulker_box
  - gray_shulker_box
  - silver_shulker_box
  - cyan_shulker_box
  - purple_shulker_box
  - blue_shulker_box
  - brown_shulker_box
  - green_shulker_box
  - red_shulker_box
  - black_shulker_box
  - shulker_shell
  - ELYTRA`

As you can see elytra is in both lists, however they are not taken from the players while other listed items are.

**Comment by kangarko** [comment] 2017-06-27 08:01
Hey,

when they are not taken? When they have elytra in the inventory or assigned in the armor slot so they can fly?

**Comment by dwaynehulsman** [comment] 2017-06-27 08:03
It's for either situation. I tried to simulate the issue with both elytra's in the inventory and armor slot.

**Comment by kangarko** [comment] 2017-06-27 14:07
I have tested it and cannot reproduce. May I see your whole settings.yml? (use pastebin.com)

**Comment by dwaynehulsman** [comment] 2017-06-28 08:14
Here you go: https://gist.github.com/fdd4596e5ef873fe7f8bf76715c6ab36

**Comment by kangarko** [comment] 2017-07-01 18:57
Hey, sorry for the delay.

Make sure the players don't have creative mode, because you have Ignore_Creative on true. Also make sure your worlds where this doesn't work aren't titled 'vanilla' nor 'vanilla_nether'.

**Comment by dwaynehulsman** [comment] 2017-07-12 11:02
Default world names, all players are either in survival or adventure mode.

**Comment by kangarko** [comment] 2017-07-14 10:59
I believe I have fixed it, please test against 1.4.0

**Comment by kangarko** [comment] 2017-07-31 09:57
Closing, please remind me if it still persists.

**Closed by kangarko** 2017-07-31 09:57 UTC
Labels: bug, issue
